= Very brief tutorial!
2018-02-20
:jbake-type: post
:jbake-status: published
:jbake-tags: scala
:idprefix:

Записался на https://www.coursera.org/learn/progfun1[первый курс] из специализации
https://www.coursera.org/specializations/scala[FP in Scala].
В подготовительных материалах к первой неделе приводится очень краткий гайд по языку в нем говорится о том,
что такое классы, трейты, объекты и пакеты.

=== Classes
Классы в Scala очень похожи на классы в Java. Они являются шаблонами для построение объектов (objects) и содержат
поля и методы. Как и в Java для создания объекта (class instantiated) ипользуется keyword *_new_*.
Так же в Scala существуют специальные типы классов, о которых узнаем позже в курсе.
Классы в Scala не имеют статических членов, для этого используются объеты.

=== Traits
Говорят, что _Traits_ похожи на Java интерфейсы, однако они могут содержать _concrete members_, тоесть реализацию
методов или определения полей.

=== Objects
В Scala отсутствуют статические поля и методы, вместо этого исполюзуется _object_. Он представляет единственный
instance (экземпляр) класса, то что называется singleton. Создать instance объекта с помощью _new_ не представляется возможным,
однако у нас есть доступ к полям и методам через имя объекта.

=== Packages
Из того, что Я понял: в Scala можно ипортировать все, объявлять импорт не только в начале файла и файл в пакете,
не обязательно должне находится в соотвественном пути из дирикторий. Пока не очень понятно. Разберемся :)

=== Hello, Scala!
Точкой входа в программу на Scala является метод объявленый в исполняемом объекте. Чтобы объект сделать исполняемым
необходимо "заэкстендить" тип App -- *_extends App_* или добавить _main_-метод -- *_def main(args: Array[String])_*.

[source, java]
----
object HelloScala extends App {
  println("Hello, Scala!")
}
----
Интересно, а что за магия проихсодит в App?

[source, java]
----
object HelloScala {
  def main(args: Array[String]) {
    println("Hello, Scala!")
  }
}
----
Говорят, что нужно использовать первый способ, c _extends App_, а не объявлением _main_-метода.
Интересно почему? Ну крому того, что так красивее :)

Не знаю, почему это называется "very brief tutorial", однако. Завтра-послезавтра буду разбираться с материалами первой
недели, а на выходных попробую осолить https://docs.scala-lang.org/tour/tour-of-scala.html[Tour of Scala],
что мне кажется больше похож на brief tutorial :)

"May the force be with your!" (C)
